### ISSUE TITLE
Ontologies for licensing data

### ISSUE THREAD

**Issue by Joralmi** [oeg-upm/auroral-core-ontology#21]
Is there an ontology we can use for licensing data? 
For instance specify if the date can be used for commercial uses or shared with third parties.
Something like the MIT or APACHE licenses for software.

**Comment by AhlemRhayem** [comment]
In the Thing description license is already defined. 

Please check this link. https://www.w3.org/2019/wot/td/v1  

Otherwise, you have another option by adding a triple to your dataset such as : 

<URI-Dataset> dct:license <https://creativecommens.org/licenses/by>
