### ISSUE TITLE
Extend the properties of the device

### ISSUE THREAD

**Issue by Joralmi** [oeg-upm/auroral-core-ontology#22]
I would like to be able to specify serialNumber and/or versionNumber for my registered devices.

Currently we have name, description, hasManufacturer and hasModel.

**Comment by AhlemRhayem** [comment]
Added properties,

The device properties are: hasCreationDate, hasName, hasStatus, hasUpdateDate (inherited from the core:Item concept).
decsription, hasManufacturer, hasModel inherited from the saref:Device concept.
hasId, versionNumber, serialNumber (defined in the core:Device)

The changes are available in Github and will be on the portal as soon as possible.
