### ISSUE TITLE
Om:Unit_Of_Measurement

### ISSUE THREAD

**Issue by juancanobenito** [oeg-upm/auroral-core-ontology#29]
We can use https://saref.etsi.org/core/UnitOfMeasure to follow the SAREF ontology instead of the om ontology.

We can extend the class UnitOfMeasure from SAREF with the rest of the OM classes.

**Comment by AhlemRhayem** [comment]
I am not sure about this proposition, does the SAREF cover the required units? 
 I checked now and it seems that the UnitOfMeasure is composed of some unit categories like (TemperatureUnit, PressureUnit) without specifying what these units are (for example, degree, etc... )

**Comment by AhlemRhayem** [comment]
I align the core ontology with the saref ontology, the new version contains the reused saref classes
