### ISSUE TITLE
Enrich sensor measurement data

### ISSUE THREAD

**Issue by Joralmi** [oeg-upm/auroral-core-ontology#3]
Hello,

I would like to include a data model for sensor measurements.
See below my proposal for standard JSON-LD for sensors:

{
  @context: --> Sensors
  @type: --> Sensor type (As for available types in VICINITY/AURORAL ontologies)
  oid: string
  iid: string --> interaction id: property or event id defined by user
  timestamp --> We can follow some standard for the timestamp too
  measurements: [
    {
      @propertyType: --> property type (From available properties in ontology)
      value: number/string
      units: string --> Should this follow an ontology? Example: celsius, meters, lumens...
    },
    ...
  ]
}

I believe all fields should be mandatory, however, If it is possible, we can extend with optional fields for particular cases that might arise.
Please let me know if this should be extended or not feasible so we can adapt it.

**Comment by mariapoveda** [comment]
The new ontology is in https://github.com/oeg-upm/auroral-adapters-ontology

It basically imports http://iot.linkeddata.es/def/adapters# from VICINITY.

**Comment by juancanobenito** [comment]
oid: string -> Is for the platform

Define the relationship between the interaction pattern and property.

Measurements

Put an example of timestamp

Show an example.

**Comment by AndreaCimminoArriaga** [comment]
Check that @propertyType is just @type

**Comment by AndreaCimminoArriaga** [comment]
{
@context: --> Sensors
@type: --> Sensor type (As for available types in VICINITY/AURORAL ontologies)
oid: string
iid: string
timestamp --> xsd:datetime
measurements: [
{
@type: --> measurement type (As for available types in VICINITY/AURORAL ontologies)
value: number/string/double
units: string --> unit from the ontology
},
...
]
}

**Comment by AndreaCimminoArriaga** [comment]
Probably the timestamp will go inside the measurements, it will depend on the @context and the ontology
