### ISSUE TITLE
Class domain in core ontology

### ISSUE THREAD

**Issue by Joralmi** [oeg-upm/auroral-core-ontology#32]
Hello, is it possible that the class core:Domain will be moved to be a child of core:Item??

Currently it is under core:Service (which is child of core:Item)

**Comment by AhlemRhayem** [comment]
core:Domain is not under the core:Service. It is a class that has an object property "hasDomain" where the "Service"  is the domain and the Core:Domain is the range.

**Comment by AhlemRhayem** [comment]
I fix this issue, Now the hasDomain Property has a domain "core:Item" and range "core:Domain"
