### ISSUE TITLE
Obtain hierarchy class of the TD properties

### ISSUE THREAD

**Issue by Joralmi** [oeg-upm/auroral-core-ontology#4]
It would be great to have a way to obtain the the classes hierarchy or related classes to each of the properties in a TD.
Options:
Consider adding endpoint to WoT Directory?
Query to the ontology?
Load the ontology on the WoT directory?

**Comment by mariapoveda** [comment]
Assign the domain to the WoT Thing.

**Comment by AhlemRhayem** [comment]
Can you please clarify more your needs of this issue, 

What do you mean by hierarchy class of the TD properties ?

**Comment by Joralmi** [comment]
In general this issue was opened for having access to the ontology programmatically (We have some uses cases in mind)
I replied by mail in more detail, but it is not urgent, also I think that for some cases we could use the JSON LD with the core ontology context.
